stages: 
    - build
    - deploy
    # - test-release
    # - pre-pro
    # - release
    # - deploy

build: # 必須定義一個名為 pages 的 job
 image: node:16.14.2
 stage: build
 script:
   - npm install
   #- npm ci
   - npm run build
   - mv public public-vue # GitLab Pages 的鉤子設定在 public 檔案夾
   - mv dist public # 重命名 dist 檔案夾 (npm run build 之後的輸出位置)
 artifacts:
   paths:
     - public # artifact path 一定要在 /public , 這樣 GitLab Pages 才能獲取
 tags :
   - event
 only :
 - backend
 - devServer
 - main


deploy-design:
  stage: deploy
  only :
    - design
  tags : 
    - event
  script:
    - lftp -u $FTP_account,$FTP_password 192.168.1.234 -e "lcd /builds/engineering-department-activityzoneteam/202309candypt/public/ ; mirror -e --exclude .git  --exclude .md  --exclude-glob *.yml -Revp . event23/design/candyPT ; quit"


deploy-dev:
  stage: deploy
  only :
  - devServer
  tags :
  - event
  script:
    - lftp -u $FTP_account,$FTP_password 192.168.1.234 -e "lcd /builds/engineering-department-activityzoneteam/202309candypt/ ; mirror -e --exclude .git --exclude .md  --exclude-glob *.yml -Revp . event23/candyPT/ ; quit"

deploy-product:
  stage: deploy
  only :
  - main
  script:
    - lftp -u $FTP_account,$FTP_password 192.168.8.102 -e "lcd /builds/engineering-department-activityzoneteam/202309candypt/public/ ; mirror -e --exclude .git  --exclude-glob *.md  --exclude-glob *.yml -Revp . event23/candyPT/ ; quit"
  #when: manual
  tags :
  - event